### ISSUE TITLE
Issues with low quality math formulas in the PDF viewer

### ISSUE THREAD

**Issue by gkaf89** [mkucej/i-librarian-free#49]
The PDF viewer seems to have issues displaying mathematical formulas that were imported as (relatively low quality) images in the document. I have uploaded a couple of documents where the problem appears in the demo library:

1. Passive filters - potentialities and limitations
2. Z-source inverter

**Comment by mkucej** [comment]
After inspecting the SVG rendering, it turns out there are no clip paths for these elements generated by the pdftocairo library. This is unfixable by us, and it seems that pdftocairo is not being developed anymore, so an upstream fix is out of the question. The proposed solution is to switch back to the raster image output, as it was in I, Librarian 4 (with all it's drawbacks).

**Comment by gkaf89** [comment]
Is there a plan to add the option to use raster image output in the PDF Viewer of future versions of Librarian 5?
